### ISSUE TITLE
winmove_agg(): Error in .local(x, row, nrows, ...) : validRow(x, row) is not TRUE

### ISSUE THREAD

**Issue by connor-french** [ropensci/grainchanger#2]
Hello Dr. Graham,

Thanks for the much needed improvement in raster aggregation! I'm conducting a test run of the winmove_agg() function on a bioclim raster for New Zealand and repeatedly run into an error: "Error in .local(x, row, nrows, ...) : validRow(x, row) is not TRUE", which I think is due to the window moving outside of the bounds of the raster, but I'm not sure. Different values of "d" still return the same error. I've attached my R code.
[winmove_test_R.txt](https://github.com/laurajanegraham/grainchanger/files/3122838/winmove_test_R.txt)
 I'm not sure if it's a problem on my end or your end. Thanks for any help!

Best,
Connor French

**Comment by laurajanegraham** [comment]
Hi Connor, 

Thanks for bringing this to my attention. It's a bit of both, but something I need to think about how to deal with. 

You are correct that it is down to the window moving outside of the bounds of the raster. Because the moving window analysis requires each cell of the grid to take data from outside, a buffer of size `d` is added. I need to have a think about how to deal with this issue. 

One thing I will point out though is that `d` should be in the same units as the input raster/grid. This means that in this case the input value of 5 is rather large. I will make sure the documentation is clearer on this fact. 

Leaving this open for now until I've added some proper error catching and documentation for this issue. 

Thanks, 

Laura

**Comment by laurajanegraham** [comment]
The error catching and documentation should all be up to date, but please let me know if you have any further issues.
